### ISSUE TITLE
Detect Ventoy

### ISSUE THREAD

**Issue by Lord-Valen** [nicholasbishop/writedisk#136]
It would be pretty neat if this could detect a Ventoy installation and offer to copy the image into Ventoy's image partition instead of writing over the device. Any Ventoy installation will have a minimum of two partitions: the first partition contains the images, the second partition will contain a `/ventoy` directory. That's probably enough information to detect any Ventoy USB devices and know where the destination directory is.

**Comment by nicholasbishop** [comment]
I think that's a reasonable idea. I have no plans to add a feature like that myself, but if it's something you're interested in working on I'm happy to review PRs :)
